# Site settings
title: Ryan Brown's Dev Portfolio and Blog
description: A portfolio site and blog for my musings on Ruby on Rails and whatever else I may come across.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ryan Brown
user_description: I'm a developer with a Ruby on Rails focus.
user_title: Software Engineer
email: ryancolorcafe@gmail.com
twitter_username: ryancolorcafe
github_username:  browneryan

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
